routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\TaskController;
use App\Http\Controllers\LogController;

use App\Models\Invoice;
use App\Models\Product;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Desafio 1
Route::get('/desafio1', function () {

    $invoice = Invoice::select(DB::raw('Sum(quantity * price) AS total'))
                     ->join('products', 'invoices.id', '=', 'products.invoice_id')
                     ->get();

    $invoices = Product::select(DB::raw('distinct(invoice_id) as ids'))
                            ->where('quantity', '>', 100)
                            ->get();

    $products = Product::select('name')
                         ->whereRaw('quantity * price > ?', [1000000])
                         ->get();

    return response()->json([
        'total' => $invoice[0]->total,
        'invoces' => $invoices->pluck('ids'),
        'products' => $products->pluck('name')  
    ]);
});

//Desafio 3
Route::get('/product', function () {

    $product = Product::create([
        'invoice_id' => 2,
        'name' => 'Product 4',
        'quantity' => 200,
        'price' => 500000
    ]);

    return response()->json([
        'product' => $product
    ]);

});

Auth::routes();

Route::get('/', function(){
    return redirect("task");
})->name('home');

Route::resource('task', TaskController::class);
Route::resource('log', LogController::class);

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $fillable = [
        'description',
        'user_id',
        'assigned_to',
        'max_execution_date'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function assigned()
    {
        return $this->belongsTo(User::class, 'assigned_to');
    }
     
    public function logs()
    {
        return $this->hasMany(Log::class);
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use Carbon\Carbon;

class TaskController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::all();
        $today = Carbon::now();

        foreach ($tasks as $key => $task) {
            $max_execution_date  = new Carbon($task->max_execution_date);
            $task->expire = (Carbon::parse($today->format('Y-m-d h:i:s'))->diffInMinutes($max_execution_date->format('Y-m-d h:i:s'), false) < 0) ? true : false;
        }

        return view('task.index', ['tasks' => $tasks]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('task.create')->with(['users' => User::where('id','!=', Auth::user()->id)->get()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'assigned_to' => 'required',
            'description' => 'required',
            'max_execution_date' => 'required|date',
        ]);
           
        $data = $request->all();

        Task::create([
            'description' => $data['description'],
            'max_execution_date' => $data['max_execution_date'],
            'assigned_to' => $data['assigned_to'],
            'user_id' => Auth::user()->id,
        ]);


        return redirect("task")->withSuccess('Task created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        if ($task->assigned_to == Auth::user()->id) {
            return view('task.show')->with(['task' => $task]);
        }

        return redirect("task")->withError('Task is not assigned to you');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        //
    }
}

resources/views/task/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row justify-content-center">
    <div class="col-md-6">
        <form action="{{ route('task.store') }}" method="post" enctype="multipart/form-data">
        @csrf
            <div class="form-group">
                <label for="description">Description</label>
                <textarea class="form-control @error('description') is-invalid @enderror" name="description" id="description" placeholder=""></textarea>
                @error('description')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror   
            </div>
            <div class="form-group">
                <label for="assigned_to">Assigned to</label>
                <select class="custom-select @error('assigned_to') is-invalid @enderror" name="assigned_to">
                    <option selected value="">Select</option>
                    @foreach ($users as $user)
                        <option value="{{$user->id}}">{{ $user->name }}</option>
                    @endforeach
                </select>
                @error('assigned_to')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="max_execution_date">Expire</label>
                <input type="datetime-local" class="form-control @error('max_execution_date') is-invalid @enderror" name="max_execution_date" id="max_execution_date">
                @error('max_execution_date')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
@endsection

resources/views/task/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="d-flex w-100 justify-content-between pb-2">
                <h3>List</h3>
                <a href="{{ route('task.create') }}" class="btn btn-primary">Add task</a>
            </div>
            @if (isset($tasks) && count($tasks) > 0) 
                <div class="list-group">
                    @foreach ($tasks as $task)
                        <a href="{{ route('task.show', $task) }}" @class(['list-group-item', 'list-group-item-action', 'danger' => $task->expire ])>
                            <div class="mb-1 px-2">
                                <div class="py-3" style="min-height: 56px; font-size:12px">
                                    <p class="mb-0">Created by {{ $task->user->name }} </p>
                                    <p class="mb-0"> {{ \Carbon\Carbon::parse($task->created_at)->format('j F, Y H:m') }}</p>
                                </div>
                                <div class="d-flex w-100">
                                    <p class="lead text-truncate">{{ $task->description }}</p>
                                </div>
                                <div class="" style="font-size:12px">
                                    <span class="text-info"> Expire: {{ \Carbon\Carbon::parse($task->max_execution_date)->format('j F, Y H:m') }}</span>   
                                    <span class="float-right">Assigned to: {{ $task->assigned->name }}</span>
                                </div>
                            </div>
                        </a>
                    @endforeach
                </div>
            @else
                <div>No data available</div>
            @endif
        </div>
    </div>
@endsection

resources/views/task/show.blade.php
@extends('layouts.app')
@section('content')
<div class="row justify-content-center">
    <div class="col-md-6 py-4" style="background: #eee; border-radius: 5px">  
        <div class="mb-1 px-2">
            <div class="py-3" style="min-height: 56px; font-size:12px">
                <p class="mb-0">Created by {{ $task->user->name }} </p>
                <p class="mb-0"> {{ \Carbon\Carbon::parse($task->created_at)->format('j F, Y H:m') }}</p>
            </div>
            <div class="d-flex w-100">
                <p class="lead">{{ $task->description }}</p>
            </div>
            <div class="" style="font-size:12px">
                <p class="text-info"> Expire: {{ \Carbon\Carbon::parse($task->max_execution_date)->format('j F, Y H:m') }}</p>   
            </div>
        </div>
        <hr>
            
        <form action="{{ route('log.store') }}" method="post">
            @csrf
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Add a comment" name="comment" aria-label="Add a comment" aria-describedby="button-addon2" required>
                @error('comment')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
                <input type="hidden" id="task_id" name="task_id" value="{{ $task->id }}">
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-secondary" type="button" id="button-addon2">Comment</button>
                </div>
            </div>
        </form>
        <ul class="list-group d-flex w-100">
            @foreach ($task->logs as $log)
                <li class="p-2 mb-1" style="list-style:none;background: #ded8d863;border-radius:5px">
                    <p class="lead px-2" style="font-size:14px; ">{{ $log->comment }}</p>
                    <p class="mb-1 float-right" style="font-size:10px; "> {{ \Carbon\Carbon::parse($log->created_at)->format('j F, Y H:m') }}</p>
                </li>
            @endforeach
        </ul>
    </div>
</div>
@endsection